// Created by iWeb 3.0.2 local-build-20110122

setTransparentGifURL('Media/transparent.gif');function applyEffects()
{var registry=IWCreateEffectRegistry();registry.registerEffects({shadow_1:new IWShadow({blurRadius:4,offset:new IWPoint(4.9497,4.9497),color:'#000000',opacity:0.500000}),shadow_2:new IWShadow({blurRadius:4,offset:new IWPoint(2.8284,2.8284),color:'#000000',opacity:0.500000}),reflection_0:new IWReflection({opacity:0.50,offset:1.00}),stroke_0:new IWEmptyStroke(),shadow_0:new IWShadow({blurRadius:4,offset:new IWPoint(4.9497,4.9497),color:'#000000',opacity:0.500000})});registry.applyEffects();}
function hostedOnDM()
{return false;}
function onPageLoad()
{loadMozillaCSS('VHDL_files/VHDLMoz.css')
adjustLineHeightIfTooBig('id1');adjustFontSizeIfTooBig('id1');adjustLineHeightIfTooBig('id2');adjustFontSizeIfTooBig('id2');adjustLineHeightIfTooBig('id3');adjustFontSizeIfTooBig('id3');adjustLineHeightIfTooBig('id4');adjustFontSizeIfTooBig('id4');adjustLineHeightIfTooBig('id5');adjustFontSizeIfTooBig('id5');adjustLineHeightIfTooBig('id6');adjustFontSizeIfTooBig('id6');adjustLineHeightIfTooBig('id7');adjustFontSizeIfTooBig('id7');adjustLineHeightIfTooBig('id8');adjustFontSizeIfTooBig('id8');adjustLineHeightIfTooBig('id9');adjustFontSizeIfTooBig('id9');adjustLineHeightIfTooBig('id10');adjustFontSizeIfTooBig('id10');adjustLineHeightIfTooBig('id11');adjustFontSizeIfTooBig('id11');adjustLineHeightIfTooBig('id12');adjustFontSizeIfTooBig('id12');adjustLineHeightIfTooBig('id13');adjustFontSizeIfTooBig('id13');adjustLineHeightIfTooBig('id14');adjustFontSizeIfTooBig('id14');adjustLineHeightIfTooBig('id15');adjustFontSizeIfTooBig('id15');adjustLineHeightIfTooBig('id16');adjustFontSizeIfTooBig('id16');adjustLineHeightIfTooBig('id17');adjustFontSizeIfTooBig('id17');adjustLineHeightIfTooBig('id18');adjustFontSizeIfTooBig('id18');adjustLineHeightIfTooBig('id19');adjustFontSizeIfTooBig('id19');adjustLineHeightIfTooBig('id20');adjustFontSizeIfTooBig('id20');adjustLineHeightIfTooBig('id21');adjustFontSizeIfTooBig('id21');adjustLineHeightIfTooBig('id22');adjustFontSizeIfTooBig('id22');adjustLineHeightIfTooBig('id23');adjustFontSizeIfTooBig('id23');adjustLineHeightIfTooBig('id24');adjustFontSizeIfTooBig('id24');adjustLineHeightIfTooBig('id25');adjustFontSizeIfTooBig('id25');adjustLineHeightIfTooBig('id26');adjustFontSizeIfTooBig('id26');adjustLineHeightIfTooBig('id27');adjustFontSizeIfTooBig('id27');adjustLineHeightIfTooBig('id28');adjustFontSizeIfTooBig('id28');adjustLineHeightIfTooBig('id29');adjustFontSizeIfTooBig('id29');adjustLineHeightIfTooBig('id30');adjustFontSizeIfTooBig('id30');adjustLineHeightIfTooBig('id31');adjustFontSizeIfTooBig('id31');Widget.onload();fixupAllIEPNGBGs();fixAllIEPNGs('Media/transparent.gif');applyEffects()}
function onPageUnload()
{Widget.onunload();}
